Repository bitops-plugins/terraform, pull requests merged in 2022-11, with the labels that each got.

#13 Adding skip-deploy bitops configuration option
  README.md
  bitops.schema.yaml
  deploy.sh
Labels: documentation

#19 Adjusted scripts validations to lowercase
  bitops.schema.yaml
  scripts/terraform_apply.sh
Labels: enhancement

#21 Updating `BITOPS_PLUGIN_DIR` to `BITOPS_INSTALLED_PLUGIN_DIR`
  deploy.sh
Labels: enhancement

#17 Update placement of stack-action from 'options' to 'cli'
  README.md
  bitops.schema.yaml
Labels: enhancement, breaking change
